"""alpaca_migration_drop_orders_capital_history

Revision ID: 32fa6adbda46
Revises: c7ce2739cfd0
Create Date: 2026-05-10 14:36:23.099012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32fa6adbda46'
down_revision: Union[str, Sequence[str], None] = 'c7ce2739cfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Supprimer la FK avant de toucher à orders
    try:
        op.drop_constraint('decisions_id_ordre_fkey', 'decisions', type_='foreignkey')
    except Exception:
        pass  # contrainte absente ou nom différent selon l'environnement

    # 2. Supprimer les tables remplacées par Alpaca
    op.drop_index(op.f('ix_capital_history_id'), table_name='capital_history')
    op.drop_table('capital_history')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id_ordre'), table_name='orders')
    op.drop_table('orders')

    # 3. Ajouter les nouvelles colonnes à decisions
    op.add_column('decisions', sa.Column('actif', sa.String(length=20), nullable=True))
    op.add_column('decisions', sa.Column('classe', sa.String(length=20), nullable=True))
    op.add_column('decisions', sa.Column('direction', sa.String(length=10), nullable=True))
    op.add_column('decisions', sa.Column('prix_entree', sa.Float(), nullable=True))
    op.add_column('decisions', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('decisions', sa.Column('take_profit', sa.Float(), nullable=True))
    op.add_column('decisions', sa.Column('taille', sa.Float(), nullable=True))
    op.add_column('decisions', sa.Column('quantite', sa.Float(), nullable=True))
    op.add_column('decisions', sa.Column('raison', sa.Text(), nullable=True))
    op.add_column('decisions', sa.Column('date_ouverture', sa.DateTime(), nullable=True))
    op.add_column('decisions', sa.Column('date_expiration', sa.Date(), nullable=True))

    # 4. Élargir id_ordre (String 20 → 100) et recréer l'index sans unique
    op.alter_column('decisions', 'id_ordre',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_decisions_id_ordre'), table_name='decisions')
    op.create_index(op.f('ix_decisions_id_ordre'), 'decisions', ['id_ordre'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('decisions_id_ordre_fkey'), 'decisions', 'orders', ['id_ordre'], ['id_ordre'])
    op.drop_index(op.f('ix_decisions_id_ordre'), table_name='decisions')
    op.create_index(op.f('ix_decisions_id_ordre'), 'decisions', ['id_ordre'], unique=True)
    op.alter_column('decisions', 'id_ordre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('decisions', 'date_expiration')
    op.drop_column('decisions', 'date_ouverture')
    op.drop_column('decisions', 'raison')
    op.drop_column('decisions', 'quantite')
    op.drop_column('decisions', 'taille')
    op.drop_column('decisions', 'take_profit')
    op.drop_column('decisions', 'stop_loss')
    op.drop_column('decisions', 'prix_entree')
    op.drop_column('decisions', 'direction')
    op.drop_column('decisions', 'classe')
    op.drop_column('decisions', 'actif')
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_ordre', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('actif', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('classe', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('statut', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('prix_entree', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('stop_loss', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('take_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('prix_actuel', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('prix_sortie', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ratio_rr', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('taille', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantite_fictive', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('confiance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raison', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pnl_latent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('atr_utilise', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('alerte', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_ouverture', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_expiration', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_cloture', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey'))
    )
    op.create_index(op.f('ix_orders_id_ordre'), 'orders', ['id_ordre'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('capital_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('capital', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('capital_history_pkey'))
    )
    op.create_index(op.f('ix_capital_history_id'), 'capital_history', ['id'], unique=False)
    # ### end Alembic commands ###
