"""initial schema

Revision ID: c7ce2739cfd0
Revises: 
Create Date: 2026-04-01 22:42:42.851490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7ce2739cfd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capital_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capital_history_id'), 'capital_history', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ordre', sa.String(length=20), nullable=False),
    sa.Column('actif', sa.String(length=20), nullable=False),
    sa.Column('classe', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('prix_entree', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('prix_actuel', sa.Float(), nullable=True),
    sa.Column('prix_sortie', sa.Float(), nullable=True),
    sa.Column('ratio_rr', sa.Float(), nullable=True),
    sa.Column('taille', sa.Float(), nullable=True),
    sa.Column('quantite_fictive', sa.Float(), nullable=True),
    sa.Column('confiance', sa.Integer(), nullable=True),
    sa.Column('raison', sa.Text(), nullable=True),
    sa.Column('pnl_latent', sa.Float(), nullable=True),
    sa.Column('atr_utilise', sa.Float(), nullable=True),
    sa.Column('alerte', sa.Text(), nullable=True),
    sa.Column('date_ouverture', sa.DateTime(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=True),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_id_ordre'), 'orders', ['id_ordre'], unique=True)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('nb_candidats', sa.Integer(), nullable=True),
    sa.Column('nb_ordres_generes', sa.Integer(), nullable=True),
    sa.Column('nb_clotures', sa.Integer(), nullable=True),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_id'), 'scan_runs', ['id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ordre', sa.String(length=20), nullable=False),
    sa.Column('signaux_techniques', sa.Text(), nullable=True),
    sa.Column('contexte_actualite', sa.Text(), nullable=True),
    sa.Column('sentiment_communaute', sa.Text(), nullable=True),
    sa.Column('risques_identifies', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('score_confiance', sa.Integer(), nullable=True),
    sa.Column('detail_score', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.Column('statut_final', sa.String(length=30), nullable=True),
    sa.Column('pnl_euros', sa.String(length=20), nullable=True),
    sa.Column('commentaire_retour', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_ordre'], ['orders.id_ordre'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_decisions_id_ordre'), 'decisions', ['id_ordre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_id_ordre'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_scan_runs_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_orders_id_ordre'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_capital_history_id'), table_name='capital_history')
    op.drop_table('capital_history')
    # ### end Alembic commands ###
